<?php

use Illuminate\Database\Seeder;

class BIENNHANTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('BIENNHAN')->delete();
        
        \DB::table('BIENNHAN')->insert(array (
            0 => 
            array (
                'id' => 305,
                'khachhang_id' => 14,
                'yeucau' => 'Cài Windows 8+ office 13',
                'dongmay' => 'Toshiba Satelite L40-A',
                'cpu' => 'i3-3227U',
                'ram' => '4GB',
                'ocung' => '500GB',
                'khac' => 'Túi xách + Sạc',
                'created_at' => '2018-12-29 00:47:27',
                'updated_at' => '2019-01-02 06:43:39',
                'tinhtrang' => 'Không nhận chuột, bàn phím kẹt phím',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            1 => 
            array (
                'id' => 307,
                'khachhang_id' => 15,
                'yeucau' => 'Lắp dùm ổ SSD, gắn thêm Caddy Bay',
                'dongmay' => 'Dell Vostro 14-3468',
                'cpu' => 'I5-7200U',
                'ram' => '4GB',
                'ocung' => '',
                'khac' => 'Nhận sạc, ổ SSD Samsung 120GB./',
                'created_at' => '2018-12-29 04:54:32',
                'updated_at' => '2019-01-02 06:43:34',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            2 => 
            array (
                'id' => 308,
                'khachhang_id' => 18,
                'yeucau' => 'Cài đặt phần mềm',
                'dongmay' => 'HP 15-da1xxx',
                'cpu' => 'i7-8565U',
                'ram' => '4GB',
                'ocung' => '931.5GB',
                'khac' => 'Nhận sạc./',
                'created_at' => '2018-12-29 12:00:32',
                'updated_at' => '2019-01-02 06:43:27',
                'tinhtrang' => 'Máy bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            3 => 
            array (
                'id' => 309,
                'khachhang_id' => 310,
                'yeucau' => 'Thay bàn phím laptop ',
                'dongmay' => 'Asus VX1',
                'cpu' => 'T2500',
                'ram' => '2GB',
                'ocung' => '150GB',
                'khac' => 'Sạc, cặp laptop, bọc xanh./',
                'created_at' => '2019-01-02 06:47:50',
                'updated_at' => '2019-01-02 08:23:12',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            4 => 
            array (
                'id' => 310,
                'khachhang_id' => 312,
                'yeucau' => 'Máy kẹt BIOS./',
                'dongmay' => 'Acer Z1402-58KT',
                'cpu' => 'i5-5200U',
                'ram' => '4GB',
                'ocung' => '500GB',
                'khac' => 'Kèm sạc./',
                'created_at' => '2019-01-02 07:26:19',
                'updated_at' => '2019-01-02 12:42:30',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            5 => 
            array (
                'id' => 311,
                'khachhang_id' => 313,
                'yeucau' => 'Cài Windows 10 + office 13, phân vùng lại',
                'dongmay' => 'Dell Vostro 15',
                'cpu' => 'i7-8550U',
                'ram' => '8GB',
                'ocung' => '931.5GB',
                'khac' => 'Kèm sạc./',
                'created_at' => '2019-01-02 08:47:41',
                'updated_at' => '2019-01-02 13:23:01',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            6 => 
            array (
                'id' => 312,
                'khachhang_id' => 318,
                'yeucau' => 'Xử lý tình trạng click trên desktop hiện cửa sổ properties./',
                'dongmay' => 'Thinkpad T440',
                'cpu' => 'i5-4300U',
                'ram' => '4GB',
                'ocung' => '120GB',
                'khac' => 'Không có phụ kiện./',
                'created_at' => '2019-01-02 20:02:03',
                'updated_at' => '2019-01-02 21:16:16',
                'tinhtrang' => 'Máy bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            7 => 
            array (
                'id' => 313,
                'khachhang_id' => 320,
                'yeucau' => 'Vệ sinh',
                'dongmay' => 'Dell',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'chống sốc',
                'created_at' => '2019-01-02 23:32:37',
                'updated_at' => '2019-01-05 03:33:19',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            8 => 
            array (
                'id' => 314,
                'khachhang_id' => 322,
                'yeucau' => 'Cài Win7 & Office 2013',
                'dongmay' => 'CPU',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => '',
                'created_at' => '2019-01-03 04:51:07',
                'updated_at' => '2019-01-03 06:03:46',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            9 => 
            array (
                'id' => 315,
                'khachhang_id' => 323,
                'yeucau' => 'Cài Win 10',
                'dongmay' => 'Lenovo',
                'cpu' => 'N3060',
                'ram' => '4',
                'ocung' => '500',
                'khac' => '',
                'created_at' => '2019-01-03 05:04:30',
                'updated_at' => '2019-01-03 07:16:16',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            10 => 
            array (
                'id' => 316,
                'khachhang_id' => 329,
                'yeucau' => 'Cài win 10, office, matlab 2013 ',
                'dongmay' => 'Dell i3 Isnpiron 14 3000 series',
                'cpu' => 'i3 4005U',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-01-04 19:20:45',
                'updated_at' => '2019-01-05 06:33:28',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            11 => 
            array (
                'id' => 317,
                'khachhang_id' => 330,
                'yeucau' => 'Cài win 10, office',
                'dongmay' => 'HP EliteBook Folio 9470M',
                'cpu' => 'i5 3437',
                'ram' => '4',
                'ocung' => '120',
                'khac' => 'Sạc',
                'created_at' => '2019-01-04 19:27:44',
                'updated_at' => '2019-01-11 00:13:37',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            12 => 
            array (
                'id' => 318,
                'khachhang_id' => 322,
                'yeucau' => 'Kiểm tra lỗi đen màn hình #314',
                'dongmay' => 'Máy bộ',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => '',
                'created_at' => '2019-01-04 19:35:27',
                'updated_at' => '2019-01-06 19:21:46',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            13 => 
            array (
                'id' => 319,
                'khachhang_id' => 331,
                'yeucau' => 'Cài đặt phần mềm',
                'dongmay' => 'Dell Inspiron 15 5570',
                'cpu' => 'i5-8250U',
                'ram' => '4GB',
                'ocung' => '1TB',
                'khac' => 'Không kèm sạc./',
                'created_at' => '2019-01-04 23:54:40',
                'updated_at' => '2019-01-06 01:15:03',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            14 => 
            array (
                'id' => 320,
                'khachhang_id' => 332,
                'yeucau' => 'PTS CS6',
                'dongmay' => 'Acer Asprise',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'Kèm sạc./',
                'created_at' => '2019-01-05 00:28:53',
                'updated_at' => '2019-01-05 03:33:44',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            15 => 
            array (
                'id' => 321,
                'khachhang_id' => 333,
                'yeucau' => 'Báo giá vỏ máy HP-r042TU',
                'dongmay' => 'Không nhận máy./',
                'cpu' => './',
                'ram' => './',
                'ocung' => './',
                'khac' => './',
                'created_at' => '2019-01-05 00:46:23',
                'updated_at' => '2019-01-06 19:22:12',
                'tinhtrang' => './',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            16 => 
            array (
                'id' => 322,
                'khachhang_id' => 334,
                'yeucau' => 'Cài đặt AutoCAD 2007',
                'dongmay' => 'HP Elitebook 8560W',
                'cpu' => './',
                'ram' => './',
                'ocung' => './',
                'khac' => 'sạc',
                'created_at' => '2019-01-05 02:46:18',
                'updated_at' => '2019-01-05 04:27:41',
                'tinhtrang' => './',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            17 => 
            array (
                'id' => 323,
                'khachhang_id' => 335,
                'yeucau' => 'Xóa Ubuntu',
                'dongmay' => 'Lenovo',
                'cpu' => 'i5-7200',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Không',
                'created_at' => '2019-01-05 23:27:12',
                'updated_at' => '2019-01-06 06:05:06',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            18 => 
            array (
                'id' => 324,
                'khachhang_id' => 337,
                'yeucau' => 'etabs crack office',
                'dongmay' => 'asus',
                'cpu' => 'pentium',
                'ram' => '4',
                'ocung' => '500gb',
                'khac' => 'sạc, chuột',
                'created_at' => '2019-01-07 00:10:12',
                'updated_at' => '2019-01-07 02:46:07',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            19 => 
            array (
                'id' => 325,
                'khachhang_id' => 338,
                'yeucau' => 'mua bàn phím mới, crack office',
                'dongmay' => 'asus ',
                'cpu' => 'x541n',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'sạc chuột balo',
                'created_at' => '2019-01-07 00:35:04',
                'updated_at' => '2019-01-07 20:02:13',
                'tinhtrang' => 'hư phím',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            20 => 
            array (
                'id' => 326,
                'khachhang_id' => 339,
                'yeucau' => 'Lỗi chỉ nghe được headphone không nghe loa ngoài.',
            'dongmay' => 'Dell Inspiron (hieuhieu2107)./',
                'cpu' => 'I5-7200U./',
                'ram' => '4GB./',
                'ocung' => '500GB./',
                'khac' => 'Nhận sạc./',
                'created_at' => '2019-01-09 01:24:23',
                'updated_at' => '2019-01-09 01:24:59',
                'tinhtrang' => 'Khôn nghe được loa, còn lại bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            21 => 
            array (
                'id' => 327,
                'khachhang_id' => 340,
                'yeucau' => 'Cài win 10, office 2010, xóa toàn bộ dữ liệu máy',
                'dongmay' => 'Asus',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'Sạc',
                'created_at' => '2019-01-09 03:28:11',
                'updated_at' => '2019-01-12 01:08:10',
                'tinhtrang' => 'Không vào được win, Loa rè, bàn phím bị hư 1 số nút U và số 7',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            22 => 
            array (
                'id' => 328,
                'khachhang_id' => 341,
                'yeucau' => 'dell i.14 mở k lên; acer không kết nối wifi dc.. máy dell cài win 10',
                'dongmay' => 'acer 4740',
                'cpu' => 'acer: i5-430',
                'ram' => 'acer 2gb',
                'ocung' => 'acer 300gb',
                'khac' => '2 sạc + laptop dell inspiron 14',
                'created_at' => '2019-01-10 06:13:02',
                'updated_at' => '2019-01-11 03:49:56',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            23 => 
            array (
                'id' => 329,
                'khachhang_id' => 342,
                'yeucau' => 'Cài win 10',
                'dongmay' => 'Asus',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'Sạc',
                'created_at' => '2019-01-10 06:18:39',
                'updated_at' => '2019-01-11 01:06:31',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            24 => 
            array (
                'id' => 330,
                'khachhang_id' => 343,
                'yeucau' => 'Xử lý loa./',
                'dongmay' => 'Thùng CPU./',
                'cpu' => './',
                'ram' => './',
                'ocung' => './',
                'khac' => 'Không phụ kiện./',
                'created_at' => '2019-01-10 20:34:37',
                'updated_at' => '2019-01-10 21:12:21',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            25 => 
            array (
                'id' => 331,
                'khachhang_id' => 344,
                'yeucau' => 'Kiểm tra lại bàn phím nút L ra ] ./',
                'dongmay' => 'Fujisu Lifebook AH56H',
                'cpu' => 'i7-3610QM',
                'ram' => '8 GB./',
                'ocung' => '500 GBB + SSD 120GB./',
                'khac' => 'Kèm sạc./',
                'created_at' => '2019-01-10 21:20:56',
                'updated_at' => '2019-01-11 19:19:59',
                'tinhtrang' => 'Lỗi bàn phím./',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            26 => 
            array (
                'id' => 332,
                'khachhang_id' => 345,
                'yeucau' => 'Cài lại win 10 + office 2013./',
                'dongmay' => 'Dell Inspiron 15R./',
                'cpu' => 'i5-3337U./',
                'ram' => '4GB./',
                'ocung' => '223.56GB',
                'khac' => 'Kèm sạc./',
                'created_at' => '2019-01-11 17:55:57',
                'updated_at' => '2019-01-11 19:18:10',
                'tinhtrang' => 'Máy bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            27 => 
            array (
                'id' => 333,
                'khachhang_id' => 347,
                'yeucau' => 'Cài win 8 /thanhphong100898',
                'dongmay' => 'Acer',
                'cpu' => 'i3 4030u',
                'ram' => '2',
                'ocung' => '500',
                'khac' => 'SẠc, túi sốc',
                'created_at' => '2019-01-11 21:14:42',
                'updated_at' => '2019-01-12 07:17:38',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            28 => 
            array (
                'id' => 334,
                'khachhang_id' => 348,
                'yeucau' => 'vệ sinh, cài win 10, office 2013',
                'dongmay' => 'asus',
                'cpu' => 'i7',
                'ram' => '',
                'ocung' => '',
                'khac' => 'sạc, chống sốc',
                'created_at' => '2019-01-11 23:41:24',
                'updated_at' => '2019-01-12 04:27:00',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            29 => 
            array (
                'id' => 335,
                'khachhang_id' => 349,
                'yeucau' => 'vệ sinh máy',
                'dongmay' => 'hp',
                'cpu' => 'i5',
                'ram' => '4',
                'ocung' => '120',
                'khac' => 'không có',
                'created_at' => '2019-01-11 23:47:22',
                'updated_at' => '2019-01-12 04:25:23',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            30 => 
            array (
                'id' => 336,
                'khachhang_id' => 348,
                'yeucau' => 'vệ sinh máy',
                'dongmay' => 'dell precision',
                'cpu' => 'i7',
                'ram' => '8',
                'ocung' => '100gb+500gb',
                'khac' => 'không có',
                'created_at' => '2019-01-11 23:56:04',
                'updated_at' => '2019-01-12 07:18:57',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            31 => 
            array (
                'id' => 337,
                'khachhang_id' => 348,
                'yeucau' => 'vệ sinh máy',
                'dongmay' => 'Asus',
                'cpu' => 'i7',
                'ram' => '8',
                'ocung' => '100gb + 500 gb',
                'khac' => 'không có',
                'created_at' => '2019-01-11 23:58:01',
                'updated_at' => '2019-01-16 01:10:35',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            32 => 
            array (
                'id' => 338,
                'khachhang_id' => 350,
                'yeucau' => 'máy chạy chậm, cài win 10, office 2010, COPY TOÀN BỘ DATA Ổ C',
                'dongmay' => 'asus',
                'cpu' => ' i3 4030u',
                'ram' => '2GB',
                'ocung' => '',
                'khac' => 'sạc',
                'created_at' => '2019-01-13 02:23:12',
                'updated_at' => '2019-01-14 19:23:32',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            33 => 
            array (
                'id' => 339,
                'khachhang_id' => 351,
                'yeucau' => 'Kiểm tra máy không nhận chuột, usb, phím. Tiến hành cài win + Vệ sinh máy, Kiểm tra tổng quát',
                'dongmay' => 'Toshiba',
                'cpu' => 'I3',
                'ram' => '2',
                'ocung' => '250',
                'khac' => 'Sạc',
                'created_at' => '2019-01-13 19:06:00',
                'updated_at' => '2019-01-17 03:03:09',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            34 => 
            array (
                'id' => 340,
                'khachhang_id' => 352,
                'yeucau' => 'máy đang chạy thì bị đứng',
                'dongmay' => 'emachines',
                'cpu' => '',
                'ram' => '3gb',
                'ocung' => '',
                'khac' => 'Sạc',
                'created_at' => '2019-01-15 23:59:23',
                'updated_at' => '2019-01-16 00:14:28',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            35 => 
            array (
                'id' => 341,
                'khachhang_id' => 353,
                'yeucau' => '123',
                'dongmay' => '12123',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => '',
                'created_at' => '2019-01-16 06:30:51',
                'updated_at' => '2019-01-17 03:03:35',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            36 => 
            array (
                'id' => 342,
                'khachhang_id' => 353,
                'yeucau' => '123',
                'dongmay' => '12123',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => '',
                'created_at' => '2019-01-16 06:30:51',
                'updated_at' => '2019-01-17 03:03:46',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            37 => 
            array (
                'id' => 343,
                'khachhang_id' => 354,
                'yeucau' => 'Vệ sinh máy , Kiểm tra quạt, Thay miếng lót bàn phím',
                'dongmay' => 'dell precision',
                'cpu' => 'i5',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'sạc',
                'created_at' => '2019-01-16 07:01:12',
                'updated_at' => '2019-01-17 07:48:35',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            38 => 
            array (
                'id' => 344,
                'khachhang_id' => 356,
                'yeucau' => 'Thay loa asus S451LA , cài win 10 ,office 2013',
                'dongmay' => 'asus S451LA',
                'cpu' => 'i5',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'sạc',
                'created_at' => '2019-01-17 07:33:21',
                'updated_at' => '2019-01-18 03:25:14',
                'tinhtrang' => 'Loa không nghe ',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            39 => 
            array (
                'id' => 345,
                'khachhang_id' => 357,
                'yeucau' => 'Lâu lâu mở không lên ',
                'dongmay' => 'asus',
                'cpu' => 'i5',
                'ram' => '4',
                'ocung' => 'SSD 120 + HDD 500',
                'khac' => 'sạc',
                'created_at' => '2019-01-17 07:40:46',
                'updated_at' => '2019-02-12 03:51:51',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            40 => 
            array (
                'id' => 346,
                'khachhang_id' => 358,
                'yeucau' => 'Thay màn hình + Vệ sinh máy',
                'dongmay' => 'Dell Inspiron 14 5447.',
                'cpu' => 'Intel i5-4210U.',
                'ram' => '4 GB.',
                'ocung' => '500 GB.',
                'khac' => 'Nhận sạc + túi chống sốc.',
                'created_at' => '2019-01-17 19:40:03',
                'updated_at' => '2019-01-18 00:47:56',
                'tinhtrang' => 'Hư màn hình.',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            41 => 
            array (
                'id' => 347,
                'khachhang_id' => 344,
                'yeucau' => 'Bàn phím loạn',
                'dongmay' => 'Fujitsu FMVA56HB',
                'cpu' => 'i7-3610QM',
                'ram' => '8',
                'ocung' => 'ssd 120GB HĐ 500GB',
                'khac' => 'Sạc',
                'created_at' => '2019-01-19 02:47:26',
                'updated_at' => '2019-01-21 02:03:21',
                'tinhtrang' => 'Bàn phím loạn',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            42 => 
            array (
                'id' => 348,
                'khachhang_id' => 360,
                'yeucau' => 'Cài Win 10,  ngôn ngữ java',
                'dongmay' => 'Asus',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'không',
                'created_at' => '2019-01-19 04:04:55',
                'updated_at' => '2019-01-20 03:05:34',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            43 => 
            array (
                'id' => 349,
                'khachhang_id' => 361,
                'yeucau' => 'Cài win Office',
                'dongmay' => 'Dell',
                'cpu' => 'i5-7th Gen',
                'ram' => 'Không biết',
                'ocung' => 'KHông biết',
                'khac' => '',
                'created_at' => '2019-01-19 06:04:55',
                'updated_at' => '2019-01-19 07:00:47',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            44 => 
            array (
                'id' => 350,
                'khachhang_id' => 362,
                'yeucau' => 'Format trắng, cài lại windows 10.',
                'dongmay' => 'HP Notebook.',
                'cpu' => 'Pentium N3710.',
                'ram' => '4 GB.',
                'ocung' => '500 GB.',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-01-20 19:59:34',
                'updated_at' => '2019-01-21 01:31:03',
                'tinhtrang' => 'Máy bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            45 => 
            array (
                'id' => 351,
                'khachhang_id' => 363,
                'yeucau' => 'Kiểm tra ổ cứng.',
                'dongmay' => 'Acer Arpire E1.',
                'cpu' => 'Intel i3-2348M.',
                'ram' => '2 GB.',
                'ocung' => 'Không xác định.',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-01-20 20:19:49',
                'updated_at' => '2019-01-21 04:09:30',
                'tinhtrang' => 'Ổ cứng kêu.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            46 => 
            array (
                'id' => 352,
                'khachhang_id' => 345,
                'yeucau' => 'Cài lại Windows 10.',
                'dongmay' => 'Như phiếu 332.',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => '',
                'created_at' => '2019-01-20 21:55:20',
                'updated_at' => '2019-01-20 21:55:38',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            47 => 
            array (
                'id' => 353,
                'khachhang_id' => 364,
                'yeucau' => 'Cài office 2013',
                'dongmay' => 'i3',
                'cpu' => '',
                'ram' => '4',
                'ocung' => '500 GB.',
                'khac' => 'không có',
                'created_at' => '2019-01-20 23:47:21',
                'updated_at' => '2019-01-21 00:09:18',
                'tinhtrang' => 'Bình thường./',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            48 => 
            array (
                'id' => 354,
                'khachhang_id' => 365,
                'yeucau' => 'máy báo sạc luôn full',
                'dongmay' => 'asus',
                'cpu' => 'i3 4030u',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'sạc',
                'created_at' => '2019-01-22 03:11:43',
                'updated_at' => '2019-01-22 03:13:16',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            49 => 
            array (
                'id' => 355,
                'khachhang_id' => 366,
                'yeucau' => 'Kiểm tra sạc & nguồn',
                'dongmay' => 'Asus',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'Sạc',
                'created_at' => '2019-01-22 10:38:26',
                'updated_at' => '2019-01-22 13:30:02',
                'tinhtrang' => 'Không sạc  được',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            50 => 
            array (
                'id' => 356,
                'khachhang_id' => 367,
                'yeucau' => 'Loa rè',
                'dongmay' => 'Dell',
                'cpu' => 'i3',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-01-22 11:29:24',
                'updated_at' => '2019-01-23 12:47:58',
                'tinhtrang' => 'Loa rè',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            51 => 
            array (
                'id' => 357,
                'khachhang_id' => 366,
                'yeucau' => 'Kiểm tra máy không lên nguồn',
                'dongmay' => 'asus',
                'cpu' => 'Không xác định',
                'ram' => 'Không xác định',
                'ocung' => 'Không xác định',
                'khac' => 'Sạc',
                'created_at' => '2019-01-23 10:39:39',
                'updated_at' => '2019-01-26 13:03:55',
                'tinhtrang' => 'Không lên nguồn',
                'tiendo' => 1,
                'nhanvien_id' => 5,
            ),
            52 => 
            array (
                'id' => 358,
                'khachhang_id' => 368,
                'yeucau' => 'cài office 2013',
                'dongmay' => 'asus',
                'cpu' => 'core i5',
                'ram' => '4',
                'ocung' => '1tb',
                'khac' => 'sạc',
                'created_at' => '2019-01-24 07:57:21',
                'updated_at' => '2019-01-24 11:05:55',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 5,
            ),
            53 => 
            array (
                'id' => 359,
                'khachhang_id' => 369,
                'yeucau' => 'Nhận máy báo giá mua máy',
                'dongmay' => 'Asus',
                'cpu' => 'I3',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-01-24 10:17:07',
                'updated_at' => '2019-01-25 02:13:13',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            54 => 
            array (
                'id' => 360,
                'khachhang_id' => 370,
                'yeucau' => 'khắc phục màn hình tối ',
                'dongmay' => 'i5',
                'cpu' => '',
                'ram' => '4',
                'ocung' => '',
                'khac' => 'sạc',
                'created_at' => '2019-01-25 07:26:56',
                'updated_at' => '2019-01-26 13:04:14',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 5,
            ),
            55 => 
            array (
                'id' => 361,
                'khachhang_id' => 371,
                'yeucau' => 'Cài Spss',
                'dongmay' => 'i5',
                'cpu' => '',
                'ram' => '4',
                'ocung' => 'HDD 500GB',
                'khac' => 'ko có',
                'created_at' => '2019-01-25 09:16:24',
                'updated_at' => '2019-01-26 13:04:25',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 5,
            ),
            56 => 
            array (
                'id' => 362,
                'khachhang_id' => 372,
                'yeucau' => 'Thay màn hình.',
                'dongmay' => 'Sony Vaio Phiếu giấy 330.',
                'cpu' => 'Không xác định.',
                'ram' => 'Không xác định.',
                'ocung' => 'Không xác định.',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-01-26 13:02:47',
                'updated_at' => '2019-01-26 13:03:38',
                'tinhtrang' => 'Lỗi màn hình.',
                'tiendo' => 1,
                'nhanvien_id' => 7,
            ),
            57 => 
            array (
                'id' => 363,
                'khachhang_id' => 322,
                'yeucau' => 'Lắp SSD 120GB + Caddy Bay',
            'dongmay' => 'HP 430 (phiếu giấy 329).',
                'cpu' => 'Pentium B960/',
                'ram' => '4 GB.',
                'ocung' => '500 GB.',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-01-26 13:08:59',
                'updated_at' => '2019-01-27 01:34:52',
                'tinhtrang' => 'Không có ổ đĩa quang.',
                'tiendo' => 1,
                'nhanvien_id' => 7,
            ),
            58 => 
            array (
                'id' => 364,
                'khachhang_id' => 311,
                'yeucau' => '#Thử nghiệm',
                'dongmay' => '#Thử nghiệm',
                'cpu' => '#Thử nghiệm',
                'ram' => '#Thử nghiệm',
                'ocung' => '#Thử nghiệm',
                'khac' => '#Thử nghiệm',
                'created_at' => '2019-01-26 18:44:33',
                'updated_at' => '2019-02-08 09:00:19',
                'tinhtrang' => '#Thử nghiệm',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            59 => 
            array (
                'id' => 365,
                'khachhang_id' => 373,
                'yeucau' => 'Cài win 7 Kiểm tra Cổng DVI trình chiếu/ Cài Office 2010',
                'dongmay' => 'HP Elitebook 8460P',
                'cpu' => 'i5 2520M',
                'ram' => '4GB ',
                'ocung' => '500GB',
                'khac' => 'Sạc',
                'created_at' => '2019-02-11 03:58:51',
                'updated_at' => '2019-02-12 03:52:07',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            60 => 
            array (
                'id' => 366,
                'khachhang_id' => 375,
                'yeucau' => 'Cài win 7 64',
                'dongmay' => 'Asus X45C',
                'cpu' => 'i3 3110M',
                'ram' => '4GB',
                'ocung' => '',
                'khac' => 'Sạc',
                'created_at' => '2019-02-11 04:23:20',
                'updated_at' => '2019-02-12 03:52:29',
                'tinhtrang' => 'Lỗi win mở không lên',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            61 => 
            array (
                'id' => 367,
                'khachhang_id' => 376,
                'yeucau' => 'Cài đặt phần mềm Camtasia 9, Premiere, crack Òffice',
                'dongmay' => 'Dell Vostro 15-3568',
                'cpu' => 'i5-7200U',
                'ram' => '4 GB',
                'ocung' => '1 TB',
                'khac' => 'Không có phụ kiện.',
                'created_at' => '2019-02-11 06:59:31',
                'updated_at' => '2019-02-12 03:54:59',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            62 => 
            array (
                'id' => 368,
                'khachhang_id' => 377,
                'yeucau' => 'Cài win 7 chia ổ c 120GB',
                'dongmay' => 'Macbook',
                'cpu' => '',
                'ram' => '',
                'ocung' => '300',
                'khac' => 'Sạc',
                'created_at' => '2019-02-11 12:21:00',
                'updated_at' => '2019-02-12 03:51:25',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            63 => 
            array (
                'id' => 369,
                'khachhang_id' => 341,
                'yeucau' => 'BẢO HÀNH: Cài lại Windows 10.',
                'dongmay' => 'ACER 4740',
                'cpu' => 'ACER: I5-430',
                'ram' => '2 GB',
                'ocung' => '300 GB',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-12 03:36:14',
                'updated_at' => '2019-02-12 10:03:02',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            64 => 
            array (
                'id' => 370,
                'khachhang_id' => 378,
                'yeucau' => 'Kiểm tra bàn phím.',
                'dongmay' => 'Dell Inspiron 14-3458',
                'cpu' => 'i3-4005U',
                'ram' => '4 GB',
                'ocung' => '500 GB',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-12 03:42:42',
                'updated_at' => '2019-02-12 11:16:10',
                'tinhtrang' => 'Liệt phím.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            65 => 
            array (
                'id' => 371,
                'khachhang_id' => 379,
                'yeucau' => 'Cài lại Windows 10.',
                'dongmay' => 'Dell Inspiron 15.',
                'cpu' => 'i3-6006U',
                'ram' => '4 GB',
                'ocung' => '',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-12 04:06:20',
                'updated_at' => '2019-02-14 06:46:32',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            66 => 
            array (
                'id' => 372,
                'khachhang_id' => 380,
                'yeucau' => 'hđ 500gb cũ cabdibay',
                'dongmay' => 'dell',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'cọc 200.000',
                'created_at' => '2019-02-12 08:28:57',
                'updated_at' => '2019-02-13 11:58:27',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            67 => 
            array (
                'id' => 373,
                'khachhang_id' => 382,
                'yeucau' => 'Cài Win 10',
                'dongmay' => 'Lenovo',
                'cpu' => 'I3',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc, Bàn phím, Chuột',
                'created_at' => '2019-02-13 06:09:24',
                'updated_at' => '2019-02-14 01:16:41',
                'tinhtrang' => 'Không sử dụng được phím, chuột',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            68 => 
            array (
                'id' => 374,
                'khachhang_id' => 383,
                'yeucau' => 'Máy bị hư kiểm tra máy',
                'dongmay' => 'hp',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Không',
                'created_at' => '2019-02-13 10:24:46',
                'updated_at' => '2019-02-20 14:14:47',
                'tinhtrang' => 'Bị rớt bể gốc',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            69 => 
            array (
                'id' => 375,
                'khachhang_id' => 376,
                'yeucau' => 'Thay SSD',
                'dongmay' => 'DELL',
                'cpu' => 'I5',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-02-14 02:40:48',
                'updated_at' => '2019-02-14 10:56:01',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            70 => 
            array (
                'id' => 376,
                'khachhang_id' => 363,
                'yeucau' => 'Thay HDD 500 Cài win 10 cài office 2016',
                'dongmay' => 'acer',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'không',
                'created_at' => '2019-02-14 04:00:59',
                'updated_at' => '2019-02-15 03:41:29',
                'tinhtrang' => 'Hư HDD không vào được win',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            71 => 
            array (
                'id' => 377,
                'khachhang_id' => 384,
                'yeucau' => 'Cài win 10 64 Office 2013',
                'dongmay' => 'Dell',
                'cpu' => 'i5 3337U',
                'ram' => '8GB',
                'ocung' => '500GB',
                'khac' => 'Sạc',
                'created_at' => '2019-02-14 07:24:02',
                'updated_at' => '2019-02-14 10:56:19',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            72 => 
            array (
                'id' => 378,
                'khachhang_id' => 311,
                'yeucau' => 'ádjfij',
                'dongmay' => 'akjsdfij',
                'cpu' => 'aksdjfijs',
                'ram' => 'aksnfkns',
                'ocung' => 'kjnaskndf',
                'khac' => '',
                'created_at' => '2019-02-15 03:38:19',
                'updated_at' => '2019-02-15 06:07:47',
                'tinhtrang' => 'ákdnfklan',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            73 => 
            array (
                'id' => 379,
                'khachhang_id' => 386,
                'yeucau' => 'Cài win 10 + office 2013',
                'dongmay' => 'macbook',
                'cpu' => 'Intel i2 Duo',
                'ram' => '2 GB',
                'ocung' => '150 GB',
                'khac' => 'Kèm sạc',
                'created_at' => '2019-02-15 08:37:20',
                'updated_at' => '2019-02-19 11:14:27',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 5,
            ),
            74 => 
            array (
                'id' => 380,
                'khachhang_id' => 387,
                'yeucau' => 'Kiểm tra máy không lên nguồn + Cài Win 10pro',
                'dongmay' => 'Sony',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Sạc',
                'created_at' => '2019-02-15 10:26:39',
                'updated_at' => '2019-02-15 14:04:09',
                'tinhtrang' => 'Hở gốc trên màn hình',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            75 => 
            array (
                'id' => 381,
                'khachhang_id' => 388,
                'yeucau' => 'cài lại win và office 2013, kiểm tra wifi',
                'dongmay' => 'hp',
                'cpu' => 'i3 4030u',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'sạc',
                'created_at' => '2019-02-15 10:48:31',
                'updated_at' => '2019-02-19 06:25:35',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            76 => 
            array (
                'id' => 382,
                'khachhang_id' => 389,
                'yeucau' => 'Kiểm tra nguồn.',
                'dongmay' => 'Thùng máy PC Super Pro',
                'cpu' => 'Không xác định',
                'ram' => 'Không xác định',
                'ocung' => 'Không xác định',
                'khac' => 'Không phụ kiện',
                'created_at' => '2019-02-16 01:08:12',
                'updated_at' => '2019-02-16 09:48:11',
                'tinhtrang' => 'Không nguồn',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            77 => 
            array (
                'id' => 383,
                'khachhang_id' => 373,
                'yeucau' => 'Kiểm tra lại máy không nhận cổng VGA, HDMI',
                'dongmay' => 'hp',
                'cpu' => 'I5',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-02-16 02:32:05',
                'updated_at' => '2019-02-16 09:48:44',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            78 => 
            array (
                'id' => 384,
                'khachhang_id' => 390,
                'yeucau' => 'Kiểm tra pin máy + thay pin',
                'dongmay' => 'Acer',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'Sạc',
                'created_at' => '2019-02-16 03:13:14',
                'updated_at' => '2019-02-16 04:33:27',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            79 => 
            array (
                'id' => 385,
                'khachhang_id' => 391,
                'yeucau' => 'Cài phần mềm Sondboxie',
                'dongmay' => 'msi',
                'cpu' => 'i5',
                'ram' => '8G',
                'ocung' => '1T',
                'khac' => 'không',
                'created_at' => '2019-02-16 06:02:40',
                'updated_at' => '2019-02-16 07:35:13',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            80 => 
            array (
                'id' => 386,
                'khachhang_id' => 392,
                'yeucau' => 'Cài win 7',
                'dongmay' => 'Dell',
                'cpu' => 'i3 4005u',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-02-16 06:45:18',
                'updated_at' => '2019-02-16 13:38:05',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            81 => 
            array (
                'id' => 387,
                'khachhang_id' => 393,
                'yeucau' => 'Cài Cad 2007 với Etab office 2003',
                'dongmay' => 'Acer',
                'cpu' => 'i5 8250U',
                'ram' => '4',
                'ocung' => '1TB',
                'khac' => 'Sạc',
                'created_at' => '2019-02-16 07:06:40',
                'updated_at' => '2019-02-16 10:09:13',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            82 => 
            array (
                'id' => 388,
                'khachhang_id' => 394,
                'yeucau' => 'Kiểm tra màn hình báo giá',
                'dongmay' => 'Toshiba',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Sạc',
                'created_at' => '2019-02-17 06:38:47',
                'updated_at' => '2019-02-19 11:19:09',
                'tinhtrang' => 'Bể gốc màn hình',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            83 => 
            array (
                'id' => 389,
                'khachhang_id' => 395,
                'yeucau' => 'Auto Cad 2007 + Etab',
                'dongmay' => 'Acer',
                'cpu' => 'I5',
                'ram' => '4',
                'ocung' => '1T',
                'khac' => 'Sạc',
                'created_at' => '2019-02-17 08:32:10',
                'updated_at' => '2019-02-19 13:33:57',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            84 => 
            array (
                'id' => 390,
                'khachhang_id' => 400,
                'yeucau' => 'Không lên Win',
                'dongmay' => 'Máy Bàn',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Không',
                'created_at' => '2019-02-19 05:35:13',
                'updated_at' => '2019-02-19 06:24:33',
                'tinhtrang' => 'Không lên win',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            85 => 
            array (
                'id' => 391,
                'khachhang_id' => 401,
                'yeucau' => 'Cad 2007 + etab',
                'dongmay' => 'acer',
                'cpu' => 'B960',
                'ram' => '2',
                'ocung' => '250G',
                'khac' => 'Sạc',
                'created_at' => '2019-02-19 05:54:33',
                'updated_at' => '2019-02-20 09:55:25',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            86 => 
            array (
                'id' => 392,
                'khachhang_id' => 402,
                'yeucau' => 'Cài Win máy + Vệ Sinh Máy',
                'dongmay' => 'acer',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Không',
                'created_at' => '2019-02-19 06:00:00',
                'updated_at' => '2019-02-20 01:31:37',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            87 => 
            array (
                'id' => 393,
                'khachhang_id' => 403,
                'yeucau' => 'Kiểm tra lỗi màn hình',
                'dongmay' => 'Dell',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Không',
                'created_at' => '2019-02-19 06:03:52',
                'updated_at' => '2019-02-20 01:31:09',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            88 => 
            array (
                'id' => 394,
                'khachhang_id' => 361,
                'yeucau' => 'Cài lại Windows 10.',
                'dongmay' => 'Dell Vostro 15-5568',
                'cpu' => 'I5-7200U',
                'ram' => '4GB ',
                'ocung' => 'Không xác định',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-19 12:10:11',
                'updated_at' => '2019-02-21 13:19:59',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            89 => 
            array (
                'id' => 395,
                'khachhang_id' => 410,
                'yeucau' => 'Cài win 8.1 office 2013',
                'dongmay' => 'DELL',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Sạc',
                'created_at' => '2019-02-19 13:29:15',
                'updated_at' => '2019-02-20 09:54:49',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            90 => 
            array (
                'id' => 396,
                'khachhang_id' => 415,
                'yeucau' => 'Cài win 8',
                'dongmay' => 'DELL',
                'cpu' => 'I5',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-02-20 07:02:44',
                'updated_at' => '2019-02-20 14:13:17',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            91 => 
            array (
                'id' => 397,
                'khachhang_id' => 416,
                'yeucau' => 'Vệ sinh máy.',
                'dongmay' => 'Dell Inspiron 15 7000 Gaming',
                'cpu' => 'i5-7300HQ',
                'ram' => '16 GB',
                'ocung' => '1 TB + SSD120GB ',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-20 08:13:32',
                'updated_at' => '2019-02-20 14:12:55',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            92 => 
            array (
                'id' => 398,
                'khachhang_id' => 417,
                'yeucau' => 'Cài lại Windows 10 + Office 2013 + LMHT + SPSS 16.0',
                'dongmay' => 'Asus P550L',
                'cpu' => 'i7-4510U',
                'ram' => '4 GB',
                'ocung' => 'Không kiểm tra',
                'khac' => 'Kèm sạc',
                'created_at' => '2019-02-20 08:19:20',
                'updated_at' => '2019-02-20 13:09:06',
                'tinhtrang' => 'Không kiểm tra',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            93 => 
            array (
                'id' => 399,
                'khachhang_id' => 309,
                'yeucau' => 'Win 64 bit, office 2010 / Báo giá vỏ',
                'dongmay' => 'Dell',
                'cpu' => 'i5 2450M',
                'ram' => '4gb',
                'ocung' => '250GB',
                'khac' => 'Sạc',
                'created_at' => '2019-02-20 11:53:50',
                'updated_at' => '2019-02-20 14:12:43',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            94 => 
            array (
                'id' => 400,
                'khachhang_id' => 419,
                'yeucau' => 'Kiểm tra máy',
                'dongmay' => 'Dell',
                'cpu' => 'Chưa xác định',
                'ram' => 'Chưa xác định',
                'ocung' => 'Chưa xác định',
                'khac' => 'Không',
                'created_at' => '2019-02-21 01:48:36',
                'updated_at' => '2019-02-22 12:10:46',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            95 => 
            array (
                'id' => 401,
                'khachhang_id' => 420,
                'yeucau' => 'Kiểm tra nguồn máy.',
                'dongmay' => 'Dell Vostro V131',
                'cpu' => 'Không xác định',
                'ram' => 'Không xác định',
                'ocung' => 'Không xác định',
                'khac' => 'Không',
                'created_at' => '2019-02-21 03:19:35',
                'updated_at' => '2019-02-25 03:09:39',
                'tinhtrang' => 'Không nguồn',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            96 => 
            array (
                'id' => 402,
                'khachhang_id' => 421,
                'yeucau' => 'Cài win 10 + Office 2013',
                'dongmay' => 'DELL',
                'cpu' => 'I5',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Sạc',
                'created_at' => '2019-02-22 01:06:04',
                'updated_at' => '2019-02-22 03:41:10',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            97 => 
            array (
                'id' => 403,
                'khachhang_id' => 422,
                'yeucau' => 'Cài đặt phần mềm iMindmap 11',
                'dongmay' => 'Acer Aspire 5',
                'cpu' => 'i3-7100U',
                'ram' => '4 GB',
                'ocung' => '500 GB',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-22 03:07:27',
                'updated_at' => '2019-02-22 12:10:01',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            98 => 
            array (
                'id' => 404,
                'khachhang_id' => 423,
                'yeucau' => 'cai office 2016',
                'dongmay' => 'Dell',
                'cpu' => 'i7',
                'ram' => '8G',
                'ocung' => '256',
                'khac' => 'Sạc',
                'created_at' => '2019-02-22 06:31:51',
                'updated_at' => '2019-02-22 12:11:04',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            99 => 
            array (
                'id' => 405,
                'khachhang_id' => 424,
                'yeucau' => 'Acer bị vô nước',
                'dongmay' => 'Acer e 15',
                'cpu' => 'i3 6100u',
                'ram' => '4gb',
                'ocung' => '500GB',
                'khac' => 'Sạc',
                'created_at' => '2019-02-23 00:54:28',
                'updated_at' => '2019-02-25 03:16:38',
                'tinhtrang' => 'Chưa xác định',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            100 => 
            array (
                'id' => 406,
                'khachhang_id' => 374,
            'yeucau' => 'cập nhật card - màn hình (nếu khó nhất thì cài win lại). ',
                'dongmay' => 'dell - 5250',
                'cpu' => 'i5',
                'ram' => '4',
                'ocung' => '500 - ssd 120gb',
                'khac' => 'sạc',
                'created_at' => '2019-02-23 10:44:39',
                'updated_at' => '2019-02-28 08:04:38',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            101 => 
            array (
                'id' => 407,
                'khachhang_id' => 425,
                'yeucau' => 'Cài office',
                'dongmay' => 'Asus',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => '',
                'created_at' => '2019-02-24 09:33:23',
                'updated_at' => '2019-02-24 09:40:06',
                'tinhtrang' => '',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            102 => 
            array (
                'id' => 408,
                'khachhang_id' => 426,
                'yeucau' => 'Cài lại Windows 10 + Ofice 13',
                'dongmay' => 'HP Notebook 14',
                'cpu' => 'i3-4030U',
                'ram' => '4 GB',
                'ocung' => '500 GB',
                'khac' => 'Kèm sạc.',
                'created_at' => '2019-02-25 02:11:34',
                'updated_at' => '2019-02-25 15:19:55',
                'tinhtrang' => 'Bình thường.',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            103 => 
            array (
                'id' => 409,
                'khachhang_id' => 309,
                'yeucau' => 'máy bị đứng, lag, kiểm tra mic ',
                'dongmay' => 'Dell',
                'cpu' => 'i5 2450M',
                'ram' => '4gb',
                'ocung' => '250GB',
                'khac' => 'sạc',
                'created_at' => '2019-02-25 08:09:56',
                'updated_at' => '2019-02-25 15:20:39',
                'tinhtrang' => 'thân máy ốp không sát nhau',
                'tiendo' => 1,
                'nhanvien_id' => 1,
            ),
            104 => 
            array (
                'id' => 410,
                'khachhang_id' => 427,
                'yeucau' => 'Cài win 10 + Lr + Pts + Pr',
                'dongmay' => 'DELL',
                'cpu' => 'I5 - 6200U',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Không',
                'created_at' => '2019-02-25 12:12:36',
                'updated_at' => '2019-02-26 11:36:42',
                'tinhtrang' => 'Bình ',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            105 => 
            array (
                'id' => 411,
                'khachhang_id' => 358,
                'yeucau' => 'Máy chóp tắt màn hình khi đang sử dụng',
                'dongmay' => 'Dell Inspiron 14 5447.',
                'cpu' => 'Intel i5-4210U.',
                'ram' => '4 GB.',
                'ocung' => '500 GB.',
                'khac' => 'sạc',
                'created_at' => '2019-02-26 06:50:52',
                'updated_at' => '2019-02-27 11:11:02',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            106 => 
            array (
                'id' => 412,
                'khachhang_id' => 428,
                'yeucau' => 'Cài office 2013',
                'dongmay' => 'DELL',
                'cpu' => 'I3 4005',
                'ram' => '4',
                'ocung' => '500',
                'khac' => 'Không',
                'created_at' => '2019-02-26 09:52:53',
                'updated_at' => '2019-02-26 09:59:32',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 2,
            ),
            107 => 
            array (
                'id' => 413,
                'khachhang_id' => 429,
                'yeucau' => 'cài Premiere 2018',
                'dongmay' => 'Lenovo ThinkPad',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'không có',
                'created_at' => '2019-02-26 09:58:51',
                'updated_at' => '2019-02-26 09:58:55',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            108 => 
            array (
                'id' => 414,
                'khachhang_id' => 430,
                'yeucau' => 'cài lại win 7, off 2007, phoptoshop,',
                'dongmay' => 'dell ',
                'cpu' => 'i3',
                'ram' => 'ram 2',
                'ocung' => '500gb',
                'khac' => 'sạc',
                'created_at' => '2019-02-27 00:40:23',
                'updated_at' => '2019-02-28 12:44:30',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            109 => 
            array (
                'id' => 415,
                'khachhang_id' => 431,
                'yeucau' => 'crack win + office',
                'dongmay' => 'hp ',
                'cpu' => 'i3',
                'ram' => '4',
                'ocung' => 'HDD 500GB',
                'khac' => 'ko có',
                'created_at' => '2019-02-27 03:58:11',
                'updated_at' => '2019-02-27 04:16:39',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 5,
            ),
            110 => 
            array (
                'id' => 416,
                'khachhang_id' => 432,
                'yeucau' => 'kiểm tra máy hay báo reset sau khi sử dụng khoảng 30 phút',
                'dongmay' => 'Gateway',
                'cpu' => 'pentium b960',
                'ram' => '4',
                'ocung' => '500GB',
                'khac' => 'sạc',
                'created_at' => '2019-02-28 07:29:41',
                'updated_at' => '2019-03-01 11:07:43',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            111 => 
            array (
                'id' => 417,
                'khachhang_id' => 358,
                'yeucau' => 'sạc kém, có tiếng kêu',
                'dongmay' => 'Dell Inspiron 14 5447.',
                'cpu' => 'Intel i5-4210U.',
                'ram' => '4 GB.',
                'ocung' => '500 GB.',
                'khac' => 'cọc 200.000, sạc',
                'created_at' => '2019-02-28 08:20:59',
                'updated_at' => '2019-02-28 11:17:48',
                'tinhtrang' => 'bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            112 => 
            array (
                'id' => 418,
                'khachhang_id' => 433,
                'yeucau' => 'cài lại win 8.1',
                'dongmay' => 'asus i5',
                'cpu' => 'i5 3337U',
                'ram' => '3',
                'ocung' => '500gb',
                'khac' => 'SẠC',
                'created_at' => '2019-02-28 08:38:49',
                'updated_at' => '2019-02-28 12:45:02',
                'tinhtrang' => 'Bình Thường, dính phím',
                'tiendo' => 1,
                'nhanvien_id' => 6,
            ),
            113 => 
            array (
                'id' => 419,
                'khachhang_id' => 434,
                'yeucau' => 'Vệ Sinh Máy, Cài Sap 2000',
                'dongmay' => 'HP',
                'cpu' => 'N/A',
                'ram' => '4GB',
                'ocung' => '500GB',
                'khac' => 'Sạc',
                'created_at' => '2019-02-28 08:53:21',
                'updated_at' => '2019-03-01 11:08:01',
                'tinhtrang' => 'Bình Thường',
                'tiendo' => 1,
                'nhanvien_id' => 4,
            ),
            114 => 
            array (
                'id' => 420,
                'khachhang_id' => 358,
                'yeucau' => 'kiểm tra micro và khi gõ bàn phím thì bị tắt màn hình',
                'dongmay' => 'Dell Inspiron 14 5447.',
                'cpu' => 'Intel i5-4210U.',
                'ram' => '4 GB.',
                'ocung' => '500 GB.',
                'khac' => 'sạc',
                'created_at' => '2019-03-01 07:27:22',
                'updated_at' => '2019-03-01 07:27:59',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 0,
                'nhanvien_id' => 3,
            ),
            115 => 
            array (
                'id' => 421,
                'khachhang_id' => 309,
                'yeucau' => 'cài win 2 máy win 7 64bit  office 2010 báo giá ssd 120+sạc dell',
                'dongmay' => 'Dell',
                'cpu' => 'i5 2450M',
                'ram' => '4gb; 2gb',
                'ocung' => '250GB',
                'khac' => 'sạc',
                'created_at' => '2019-03-01 08:37:16',
                'updated_at' => '2019-03-01 14:00:10',
                'tinhtrang' => 'Bình thường',
                'tiendo' => 1,
                'nhanvien_id' => 3,
            ),
            116 => 
            array (
                'id' => 422,
                'khachhang_id' => 437,
                'yeucau' => 'máy mở nguồn không lên, từng bị rơi',
                'dongmay' => 'dell',
                'cpu' => 'chưa rõ',
                'ram' => 'chưa rõ',
                'ocung' => 'chưa rõ',
                'khac' => 'sạc',
                'created_at' => '2019-03-02 01:53:39',
                'updated_at' => '2019-03-02 01:53:39',
                'tinhtrang' => 'từng bị rơi',
                'tiendo' => 0,
                'nhanvien_id' => 3,
            ),
            117 => 
            array (
                'id' => 423,
                'khachhang_id' => 438,
                'yeucau' => 'Máy không lên nguồn',
            'dongmay' => 'CPU (Máy bàn)',
                'cpu' => '',
                'ram' => '',
                'ocung' => '',
                'khac' => 'Không',
                'created_at' => '2019-03-03 02:32:08',
                'updated_at' => '2019-03-03 02:32:08',
                'tinhtrang' => 'Không lên nguồn',
                'tiendo' => 0,
                'nhanvien_id' => 3,
            ),
        ));
        
        
    }
}
